/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.company.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-03-09")
public class InvalidRequest extends org.apache.thrift.TException implements org.apache.thrift.TBase<InvalidRequest, InvalidRequest._Fields>, java.io.Serializable, Cloneable, Comparable<InvalidRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("InvalidRequest");

  private static final org.apache.thrift.protocol.TField WHAT_O_FIELD_DESC = new org.apache.thrift.protocol.TField("whatO", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField WHAT_HAPPENS_FIELD_DESC = new org.apache.thrift.protocol.TField("whatHappens", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new InvalidRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new InvalidRequestTupleSchemeFactory();

  public int whatO; // required
  public java.lang.String whatHappens; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WHAT_O((short)1, "whatO"),
    WHAT_HAPPENS((short)2, "whatHappens");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WHAT_O
          return WHAT_O;
        case 2: // WHAT_HAPPENS
          return WHAT_HAPPENS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WHATO_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WHAT_O, new org.apache.thrift.meta_data.FieldMetaData("whatO", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.WHAT_HAPPENS, new org.apache.thrift.meta_data.FieldMetaData("whatHappens", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(InvalidRequest.class, metaDataMap);
  }

  public InvalidRequest() {
  }

  public InvalidRequest(
    int whatO,
    java.lang.String whatHappens)
  {
    this();
    this.whatO = whatO;
    setWhatOIsSet(true);
    this.whatHappens = whatHappens;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public InvalidRequest(InvalidRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    this.whatO = other.whatO;
    if (other.isSetWhatHappens()) {
      this.whatHappens = other.whatHappens;
    }
  }

  public InvalidRequest deepCopy() {
    return new InvalidRequest(this);
  }

  @Override
  public void clear() {
    setWhatOIsSet(false);
    this.whatO = 0;
    this.whatHappens = null;
  }

  public int getWhatO() {
    return this.whatO;
  }

  public InvalidRequest setWhatO(int whatO) {
    this.whatO = whatO;
    setWhatOIsSet(true);
    return this;
  }

  public void unsetWhatO() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WHATO_ISSET_ID);
  }

  /** Returns true if field whatO is set (has been assigned a value) and false otherwise */
  public boolean isSetWhatO() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WHATO_ISSET_ID);
  }

  public void setWhatOIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WHATO_ISSET_ID, value);
  }

  public java.lang.String getWhatHappens() {
    return this.whatHappens;
  }

  public InvalidRequest setWhatHappens(java.lang.String whatHappens) {
    this.whatHappens = whatHappens;
    return this;
  }

  public void unsetWhatHappens() {
    this.whatHappens = null;
  }

  /** Returns true if field whatHappens is set (has been assigned a value) and false otherwise */
  public boolean isSetWhatHappens() {
    return this.whatHappens != null;
  }

  public void setWhatHappensIsSet(boolean value) {
    if (!value) {
      this.whatHappens = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case WHAT_O:
      if (value == null) {
        unsetWhatO();
      } else {
        setWhatO((java.lang.Integer)value);
      }
      break;

    case WHAT_HAPPENS:
      if (value == null) {
        unsetWhatHappens();
      } else {
        setWhatHappens((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case WHAT_O:
      return getWhatO();

    case WHAT_HAPPENS:
      return getWhatHappens();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case WHAT_O:
      return isSetWhatO();
    case WHAT_HAPPENS:
      return isSetWhatHappens();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof InvalidRequest)
      return this.equals((InvalidRequest)that);
    return false;
  }

  public boolean equals(InvalidRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_whatO = true;
    boolean that_present_whatO = true;
    if (this_present_whatO || that_present_whatO) {
      if (!(this_present_whatO && that_present_whatO))
        return false;
      if (this.whatO != that.whatO)
        return false;
    }

    boolean this_present_whatHappens = true && this.isSetWhatHappens();
    boolean that_present_whatHappens = true && that.isSetWhatHappens();
    if (this_present_whatHappens || that_present_whatHappens) {
      if (!(this_present_whatHappens && that_present_whatHappens))
        return false;
      if (!this.whatHappens.equals(that.whatHappens))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + whatO;

    hashCode = hashCode * 8191 + ((isSetWhatHappens()) ? 131071 : 524287);
    if (isSetWhatHappens())
      hashCode = hashCode * 8191 + whatHappens.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(InvalidRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetWhatO()).compareTo(other.isSetWhatO());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWhatO()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.whatO, other.whatO);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetWhatHappens()).compareTo(other.isSetWhatHappens());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWhatHappens()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.whatHappens, other.whatHappens);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("InvalidRequest(");
    boolean first = true;

    sb.append("whatO:");
    sb.append(this.whatO);
    first = false;
    if (!first) sb.append(", ");
    sb.append("whatHappens:");
    if (this.whatHappens == null) {
      sb.append("null");
    } else {
      sb.append(this.whatHappens);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class InvalidRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InvalidRequestStandardScheme getScheme() {
      return new InvalidRequestStandardScheme();
    }
  }

  private static class InvalidRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<InvalidRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, InvalidRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // WHAT_O
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.whatO = iprot.readI32();
              struct.setWhatOIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // WHAT_HAPPENS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.whatHappens = iprot.readString();
              struct.setWhatHappensIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, InvalidRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(WHAT_O_FIELD_DESC);
      oprot.writeI32(struct.whatO);
      oprot.writeFieldEnd();
      if (struct.whatHappens != null) {
        oprot.writeFieldBegin(WHAT_HAPPENS_FIELD_DESC);
        oprot.writeString(struct.whatHappens);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class InvalidRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InvalidRequestTupleScheme getScheme() {
      return new InvalidRequestTupleScheme();
    }
  }

  private static class InvalidRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<InvalidRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, InvalidRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetWhatO()) {
        optionals.set(0);
      }
      if (struct.isSetWhatHappens()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetWhatO()) {
        oprot.writeI32(struct.whatO);
      }
      if (struct.isSetWhatHappens()) {
        oprot.writeString(struct.whatHappens);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, InvalidRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.whatO = iprot.readI32();
        struct.setWhatOIsSet(true);
      }
      if (incoming.get(1)) {
        struct.whatHappens = iprot.readString();
        struct.setWhatHappensIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

